### ISSUE TITLE
Bootstrap 3

### ISSUE THREAD

**Issue by hekto** [lauren/pick-a-color#21]
Bootstrap 3 is around the corner! Have you done any work on adapting the color picker?

**Comment by Diegovap** [comment]
Hi.
when i do $(".my_color_picker_class").pickAColor() two times, te picker doesn't show well.
is there any method to destroy the picker like  $(".my_color_picker_class").pickAColor('destroy') to resolve the bug????
if not....how can i destroy the picker from my class '.my_color_picker_class'?
Thanks.
