### ISSUE TITLE
Clicking on pc's with touch enabled screens [Chrome]

### ISSUE THREAD

**Issue by usajusaj** [lauren/pick-a-color#50]
There is a bug when using chrome on laptops (or any other devices with touchscreen). The library detects touch capabilities and completely ignores click events. Our workaround simply disables touch detection in line 13, but it would be great it the library would enable both input methods.

Keep up with the great work!
usajusaj

**Comment by billyaraujo** [comment]
Yes I also implemented this workaround would be better to have touch disabled by option.
