### ISSUE TITLE
values are not update on input value field

### ISSUE THREAD

**Issue by darkworks** [lauren/pick-a-color#84]
so i checked demo it :: http://lauren.github.io/pick-a-color/

changed colors it demo but new colors values are not updated to input value field 

`<input type="text" value="fff" name="desktop-demo" class="pick-a-color form-control">`

so how to do it , because  without its useless as if i have to send color value in form

**Comment by gbaumgart** [comment]
same here

**Comment by darkworks** [comment]
on form post , selected color value is submit , just that it run time it now show value change as you change color
